[phases.setup]
aptPkgs = ["python3", "python3-pip"]

[phases.build]
cmds = ["pip install --upgrade pip", "pip install -r backend/requirements.txt"]

[phases.start]
cmds = ["uvicorn backend.main:app --host 0.0.0.0 --port $PORT"]
